language: java
deploy:
  provider: heroku
  api_key:
    secure: rB2gzgEvmuvQE0Iwjj+PxnjgQSnXevLsZS9tfAYjYsbSQ7xucTZHBw9Jog3Vas9rIRrpPJilXF1d86/24bnTOvR7NGtxXOHfRISpS/1oA72JLTsjXKLW36xTJn9T7VW5RO/si6sd2KkxcIc2zLk7qStE4AG9S1MLgj3yCXKBl8P6oKoo22lsX/hTfKNeFfm7hOAyjkzTohSVAwTuUiBTvPIlk6Gr9/xTKQ/+yij0Ki5QbFvJEXrHYuwTowtaSsvwxFVSbKu71OIIgQ0ITuw+wZFEZBQgtsGeKmPo/bzlxbA1eRgCz4jIqVB2mHW43HINY4XHud9UHDsl2L9xlchEycLAdWq9W9J470LROA9GEMgoaW3T4pYYJPLxnlNR0I0TDhepdBWcpW+KbvyvEN0ykz53hgi3eHyj3wNqsGkr35Y7pnHyohuyJ1qI9eNhZA6WnwYK71UNt8odleiXVbjNOiPsJQcwMg28iwg9RsLAN6lFn4RelRiWRy3wNdz1RGjQVzAZTbsgXa//ssubZXJ+KwhBHU3ovJHB+OWEJhoKO+fpKpdPrimFSx6gCtwbJJbEZztCPdencbMUpAsNY9SDE4lXPEk0C8MfiDn0gPQ6ybCmo0fgs+V9UNzdjD6gcPgUKCnh/RkvZdyd2fgmjzVZ0qbAiiaRNaR64NDOyLya0r0=
  app: iot-bath-climate
  on:
    repo: Rshalika/bath-climate
